### ISSUE TITLE
can't see all setthings

### ISSUE THREAD

**Issue by MurkBRA** [schomery/privacy-settings#1]
Need a scrollbar.
![6cd8240339](https://cloud.githubusercontent.com/assets/12011370/8490785/61b3cfe0-2105-11e5-8995-81c1628bc092.png)

**Comment by schomery** [comment]
Can you confirm the fix on this developer version,
https://github.com/schomery/privacy-settings/blob/master/src/executables/extension.xpi?raw=true

Download the XPI file and drop it into your firefox

**Comment by MurkBRA** [comment]
Yep, now display correctly.
Thank you.
