### ISSUE TITLE
option to disable activity stream

### ISSUE THREAD

**Issue by n8v8R** [schomery/privacy-settings#100]
`browser.newtabpage.activity-stream.enabled` 
`browser.newtabpage.activity-stream.feeds.telemetry`
`browser.newtabpage.activity-stream.telemetry.ping`

collection user data and thus it would be a good fit for privacy settings

**Comment by schomery** [comment]
not possible anymore. We can only change things Mozilla offers here https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/privacy

WebExtension limitation!
