### ISSUE TITLE
referrersEnabled blocks Origin header as well

### ISSUE THREAD

**Issue by mamciek** [schomery/privacy-settings#101]
When `referrersEnabled` is enabled then not only no `Referer` header is sent but also no `Origin` header. It breaks CORS and causes many sites to break. I would like to have an option to block `Referer` header without blocking `Origin` header. I am using Firefox 57 and WebExtension.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Origin
https://github.com/schomery/privacy-settings/issues/82

**Comment by schomery** [comment]
Sorry, not doable. WebExtension is very limited. We can only ask FF to change this preference on or off; https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/privacy

That's the reason why we have that compatible mode.
