### ISSUE TITLE
preferences such as network.captive-portal-service.enabled are not listed at addons.mozilla.org

### ISSUE THREAD

**Issue by grahamperrin** [schomery/privacy-settings#104]
From [network.captive-portal-service.enabled](https://github.com/schomery/privacy-settings/issues/81):

> … we will have this in the advanced settings page.

## AMO

`network.captive-portal-service.enabled` is not in the _complete list_ at https://addons.mozilla.org/addon/privacy-settings/

**Comment by schomery** [comment]
The new webextension is limited to whatever Mozilla allows on https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/privacy

There is no way to change internal preferences anymore.

**Comment by grahamperrin** [comment]
@schomery hi, when you next work with AMO, maybe update the screenshot(s). 

(Is https://addons.cdn.mozilla.net/user-media/previews/full/161/161746.png a shot of a legacy version?)
