### ISSUE TITLE
signon.autofillForms

### ISSUE THREAD

**Issue by grahamperrin** [schomery/privacy-settings#105]
## Enhancement request

Add two preferences: 

- `signon.autofillForms`
- `signon.autofillForms.http`

It's traditional for `signon.autofillForms` to be `false` by default. From a privacy perspective, there's now a reasonable argument for it to be `true`. 

## Related

https://github.com/MrAlex94/Waterfox/issues/352

**Comment by schomery** [comment]
The new webextension is limited to whatever Mozilla allows on https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/privacy

There is no way to change internal preferences anymore.
