### ISSUE TITLE
Pref geo.wifi.logging.enabled

### ISSUE THREAD

**Issue by Gitoffthelawn** [schomery/privacy-settings#11]
There is a pref geo.wifi.logging.enabled that when *disabled* results in a red 'X' in Privacy Settings.

Is that backwards of how it should be?

**Comment by schomery** [comment]
This is what I get

<img width="496" alt="screen shot 2015-09-15 at 13 58 31" src="https://cloud.githubusercontent.com/assets/11704051/9873015/4e2f9ea8-5bb2-11e5-8325-7aad7f9da010.png">
<img width="446" alt="screen shot 2015-09-15 at 13 58 45" src="https://cloud.githubusercontent.com/assets/11704051/9873016/4eb31c1a-5bb2-11e5-9604-e4087084334a.png">

Seems fine to me

**Comment by Gitoffthelawn** [comment]
I get the opposite.  When it is toggled off, the red 'X' appears.

**Comment by schomery** [comment]
Can you check this on a clean profile,
https://support.mozilla.org/en-US/kb/profile-manager-create-and-remove-firefox-profiles

**Comment by Gitoffthelawn** [comment]
I tried toggling the pref back and forth (from off, to on, to off again).  After doing this, the indicator changed from a red 'X' in the off position to a green checkmark.

Does this pref exist by default?  I'm guessing that if the pref does not exist at all, Privacy Settings shows a red 'X' and 'off' for that item.

**Comment by schomery** [comment]
I just removed this preference. I believe there is no need for this as it is not defined by default. Thanks for the follow up

**Comment by Gitoffthelawn** [comment]
You're welcome. :-)

Sometimes prefs are not defined by default, but when set still have an impact.

I have not had the time to search through the Firefox code to see how geo.wifi.logging.enabled is handled.

The source for Firefox is at https://mxr.mozilla.org/ if you or anyone else has time to take a look.
