### ISSUE TITLE
uBlock to fill the gap?

### ISSUE THREAD

**Issue by amilopowers** [schomery/privacy-settings#12]
Hi

First thank you for your amazing addon!

Question: Does uBlock with its different malware filters replace the Google "protection" your addon disables (in your opinion)?

**Comment by berrythesoftwarecodeprogrammar** [comment]
im not sure if it exactly replaces the google safebrowsing features, but uBlock/uMatrix do have lots of malware lists available for blocking, so i use them instead. and also if you add the Disconnect lists, you can turn off 'privacy.trackingprotection.enabled'. i think if uBlock/uMatrix are in use, its better to just use the blocking on them instead of having the browser also do checking and blocking. especially when the browser features talk to google

**Comment by amilopowers** [comment]
Thanks!

I use uBlock, Reqest Policy, NoScript, Self Destructing Cookies, Privacy Settings, Privacy Badger (Desktop), Random Agent Spoofer (Desktop). And I dont send http headers, Spoof my Wifi Mac addr. (Mac only I didn't get how to do it in Fedora yet). DNS crypt is there (Mac). And of course I use Tor. Do you think that is a good setup?

**Comment by berrythesoftwarecodeprogrammar** [comment]
yeah sounds good. i dont remember what privacy badger does or how helpful it is, but i do pretty much everything else you do. ive recently switched from request policy to uMatrix (https://github.com/gorhill/uMatrix) which is a lot more powerful. u may want to check this out too https://github.com/pyllyukko/user.js . theres always room for improvement, but ur current setup seems fine. i also suggest uBlock origin if u arent using that already https://github.com/gorhill/uBlock

**Comment by amilopowers** [comment]
I think Priv. Badger does somehow the same as Self Dest. Cookies https://www.eff.org/privacybadger. I've heard of uMatrix and I am going to try it, thanks. Yes I changed to uBlock origin. 

I forgot BetterPrivacy on my Mac because I have to have Flash Player (for zattoo.com). It kills all the super cookies. 

Just recently I installed http://patrol.psyced.org/ Certificate Patrol bu I am not sure yet if it really does improve security.

Do you know how to randomly spoof a Wifi Mac address on Linux (Fedora)?

**Comment by amilopowers** [comment]
With uMatrix it seems like I dont need Random Agent Spoofer anymore. Right?

**Comment by berrythesoftwarecodeprogrammar** [comment]
you do. random agent spoofer spoofs your useragent and some other things. umatrix is like request policy. what i do is make it block everything by default except for css and images on 1st-parties. then when i visit websites i allow scripts,cookies,etc as needed. this makes the main functionality of noscript unecessary too. however noscript offers additonal protection apart from whitelisting scripts. so keep noscript installed if ur gonna block scripts by default on umatrix, and just set noscript to allow scripts globally (umatrix will manage them instead)

**Comment by berrythesoftwarecodeprogrammar** [comment]
i stopped using certpatrol a while ago, probably because it got annoying. but i think it helps if youre bothered to check every cert change etc. i use https-everywhere and https-finder.
refcontrol to have fine control over referrer information. i use uacontrol along with useragent-js-fixer too (for when i want fine tuning of useragent for sites, otherwise random agent spoofer takes care of them). once you try out a bunch of these addons together you see how they work and which ones compliment each other

**Comment by berrythesoftwarecodeprogrammar** [comment]
other useful addons: CanvasBlocker, Calomel SSL Validation, Controle de Scripts, Disable DHE, Google Privacy, NoRedirect, RightToClick, SSL Version Control, Y U no validate

**Comment by amilopowers** [comment]
I love the idea of https-finder. But is it still maintained? I looks like the project died some two years ago... Yes I do use everywhere as well.
I cant fnd the icon of Random Agent Spoofer anymore. That's why it annoys me so much. But now Panopticlick says that I am trackable...
Thanks I will look through all of these addons...

**Comment by berrythesoftwarecodeprogrammar** [comment]
i think uBlock+uMatrix with the right lists makes PrivacyBadger, ghostery and all that unnecessary. betterprivacy is a good addon though

**Comment by amilopowers** [comment]
I love the idea of https-finder. But is it still maintained? I looks like the project died some two years ago... Yes I do use everywhere as well.
I cant fnd the icon of Random Agent Spoofer anymore. That's why it annoys me so much. But now Panopticlick says that I am trackable...
Thanks I will look through all of these addons...

**Comment by amilopowers** [comment]
PrivacyBadger is good for my GF oder Mum because they don't have to care how the addons works. It just does.

**Comment by amilopowers** [comment]
SSL Version Control is obsolete I guess since old SSL is disabled in FF since a few versions.

**Comment by berrythesoftwarecodeprogrammar** [comment]
yeah. https finder still works for me idk. i think ublock is good for unsavvy users too. ive installed it on my familys' computers

**Comment by berrythesoftwarecodeprogrammar** [comment]
oh and i dont know how to spoof mac address on linux. i think i did it once though and it was probably easy. i use TMAC on windows

**Comment by amilopowers** [comment]
I don't own or use a Windows computer where I have admin rights. I use WiFiSpoof on the Mac but it isn't FOSS.

My GF hated uBlock because of that gray window when it blocks a page trying to forward.

I like the way uMatrix works! Thank you. So I have disabled NoScript (allowing all scripts) and it still takes care of XSS, ClearClick and ABE (looks still like Adblock Edge to me)?

**Comment by berrythesoftwarecodeprogrammar** [comment]
i think theyre working on fixing that so it gives an option to forward to the right site (if its a redirect)

lol, yeah it still takes care of the rest

**Comment by amilopowers** [comment]
There are two buttons: 1. "visit temporarily" and 2. "permanently". It was "only" a redirect to a Pdf...

**Comment by berrythesoftwarecodeprogrammar** [comment]
what was the site and why was it blocked? if its an actual issue/mistake you should report it. but so far for me, its only blocked things for good reason

**Comment by berrythesoftwarecodeprogrammar** [comment]
we can take this chat elsewhere if you want. its kind of gone off topic maybe, if it wasnt from the beginning

**Comment by amilopowers** [comment]
Yes you are right... What do you suggest? I don't use Skype ;-)

**Comment by berrythesoftwarecodeprogrammar** [comment]
contact details r on http://berrycckr666acln.onion/me or https://berr.yt/me
