### ISSUE TITLE
Status indicators are confusing

### ISSUE THREAD

**Issue by jomo** [schomery/privacy-settings#14]
There are three status indicators for each setting and it's not very intuitive.
At the first look I was quite confused about *what* they are indicating.

![screenshot](https://i.imgur.com/fXhfucG.png)

It took a while until I realized the check/cross marks indicate if a *feature* is enabled while the switch *and* text indicate if a *setting* is enabled.

![screenshot](https://i.imgur.com/riyjFb8.png)

The cause of this confusion is actually bad (if any?) naming conventions for settings in Firefox, i.e. using `foo.enabled = true/false` and `bar.disabled = true/false`.

However, I feel the redundant text next to the switch is adding more confusion. You might want to consider removing one of the two.

**Comment by Gitoffthelawn** [comment]
*It took a while until I realized the check/cross marks indicate if a feature is enabled while the switch and text indicate if a setting is enabled.*

This is different from my understanding of the UI.  I think the check/cross marks indicate if the setting is set to the most private option.

**Comment by berrythesoftwarecodeprogrammar** [comment]
maybe move the tick/cross column to the right of the on/off column and maybe make the toggle buttons for each setting show their actual values. e.g. 'true' or 'false' or '1' or '0' etc. and maybe add column headers. tick/cross header could be 'recommended' or 'private'

**Comment by anaran** [comment]
@jomo "Bad UI" is a pretty bad issue title. How about a short sentence stating the problem clearly?

I am not affiliated with the add-on, just felt the itch to report an issue with your issue.

**Comment by jomo** [comment]
@anaran you're right, sorry. I changed the title.

**Comment by jomo** [comment]
> This is different from my understanding of the UI. I think the check/cross marks indicate if the setting is set to the most private option.

That seems right and proves my point about confusion.
How about removing the green check mark and replacing the red cross with a :warning: icon?

**Comment by Gitoffthelawn** [comment]
@jomo I think your suggestion is a step in the right direction.  OTOH, I think a exclamation-triangle is a bit severe.  Perhaps there is something more mellow that could convey the message, or even a different approach.

I also think there may be a bug in that **when a pref does not exist**, Privacy Settings shows the red 'X', even when the default implied value is consistent with the most private option.  I have not had time to confirm this and completely flush out the issue.

**Comment by geokis** [comment]
Jomo objection is right. It takes a couple of seconds to understand the indications. 
A less confusing and gentler solution is maybe, the indication of a "**safe**"-setting with the privacy-settings Symbol.

Example:
![unbenannt-1](https://cloud.githubusercontent.com/assets/7952956/10713291/1b096404-7ab7-11e5-8c45-09f388601463.png)

**Comment by Gitoffthelawn** [comment]
I think we are definitely heading in the right direction.

Let's look at the actual tasks, from a users' point of view: People want to be able to toggle settings and know if the current value of that setting increases (or decreases) privacy and/or security.

Consequently, in addition to the on/off toggle, perhaps it would be ideal to have two rows of additional icons, one indicating privacy, and other other indicating security.  The shield for privacy, and a lock for security are good possibilities.  Another possibility for the privacy icon would be mask from browser's Private Window functionality.

If a setting's value provides increased privacy, it can have a green shield/mask.  If a setting's value provides decreased privacy, it can have a red shield/mask.  If it is a security setting (and not a privacy setting), it can have a dimmed (light gray) shield/mask.  Adjacent to the shield/mask icon can be a lock icon which similarly reflects whether or not the current setting increases or decreases security.

What do you think?

**Comment by schomery** [comment]
How about happy and sad faces?
![screen shot 2015-10-27 at 11 43 41](https://cloud.githubusercontent.com/assets/11704051/10752644/55e5f49e-7ca0-11e5-9c9b-fb5e55b12e60.png)

**Comment by jomo** [comment]
@schomery that's barely different to how it's now.

I think @Gitoffthelawn's approach is much better.
Ideally there would be 3 elements: A :lock: for security, a ![shield](https://raw.githubusercontent.com/schomery/privacy-settings/089e471d993b406ab172ad22e1bff7902f245075/src/data/icons/16.png) for privacy, and a switch to toggle the setting.

IMO the two icons should just be either grayed out or not grayed out, to keep it simple and intuitive.
Also the redundant status text next to the switch could be removed.

And ideally, clicking e.g. the privacy icon could set the setting to be private.

**Comment by schomery** [comment]
![screen shot 2015-11-09 at 12 46 13](https://cloud.githubusercontent.com/assets/11704051/11030049/b1b5e38e-86e0-11e5-8a2f-1264e1610ec5.png)

how about now?

**Comment by schomery** [comment]
icons for private and secure states need to be selected from http://fontello.com/

**Comment by jomo** [comment]
That's a lot better!

Though, I think using grayed out vs. black color (instead of colored background) looks a lot cleaner.
And perhaps use the `shield` icon for privacy options so it's consistent with Firefox' Tracking Protection:

![firefox tracking protection](https://i.imgur.com/7djopKq.png)

**Comment by schomery** [comment]
Here is the XPI if anybody would like to give it a try,
https://github.com/schomery/privacy-settings/blob/master/src/executables/extension.xpi?raw=true

Guys, please check all the prefs and make a note if you believe we need to add/remove privacy/security badge for the pref.

@jomo the new color scheme looks like this
![screen shot 2015-11-09 at 13 15 07](https://cloud.githubusercontent.com/assets/11704051/11030531/f6d55a82-86e3-11e5-8235-dfeafcd9f5a6.png)

**Comment by jomo** [comment]
:+1: almost perfect, now it just needs the fontawesome "shield" icon instead of the "eye" and "eye-off".
I tried updating it myself but failed to changed the icon :/

**Comment by schomery** [comment]
so this would be how it looks like with the shield icon
![screen shot 2015-11-09 at 16 13 44](https://cloud.githubusercontent.com/assets/11704051/11033987/1a8bb4ee-86fd-11e5-9f57-88cadc6a9bf1.png)

**Comment by jomo** [comment]
perfect IMO :shipit:

**Comment by Gitoffthelawn** [comment]
I think it's fantastic.  A huge improvement!

I do have some mixed thoughts on the shield.  I don't have time to search through the fonts right now, but is there anything like the mask from Firefox's Private Browsing?  Actually, come to think of it, that icon is included multiple places in the Firefox resources, so perhaps one of them can be used directly.

Also, for what purpose does the lock icon serve?  Is Privacy Settings now locking certain settings?

**Comment by jomo** [comment]
The lock icon is for security-related settings, the shield is used for privacy-related settings. Both are used by Firefox as well.

**Comment by Gitoffthelawn** [comment]
My error.  I was very rushed when I wrote that.  Sorry.  I meant the key icon.  What function does it serve?

In regards to the other icons: Personally, when I think of a shield, I think more of security than privacy, which is why I suggest the mask icon from Firefox's Private Browsing for the privacy indicators.  But either way, it's a huge improvement.

May want to consider appropriate tooltips as well.

**Comment by jomo** [comment]
You're right, Firefox actually uses the shield for the privacy *blocker*, and did use it in the past when mixed content was *blocked*. I had a quick look on the icons but there doesn't seem to be anything like the mask.

Maybe stick to the eye icons (as in 'being watched') then?

>  I meant the key icon. What function does it serve?

Apparently it's possible to lock a preference, I assume it cannot be changed when locked, but it's unclear to me what exactly it does or how to lock preferences.
Though the [readme](https://github.com/schomery/privacy-settings/blob/0e196407f50ad40b98a6e5745b8d1267556c5e83/ReadMe.md) has some info on how to achieve locking programmatically.

**Comment by schomery** [comment]
> Apparently it's possible to lock a preference, I assume it cannot be changed when locked, but it's unclear to me what exactly it does or how to lock preferences.

Read http://kb.mozillazine.org/Locking_preferences

> May want to consider appropriate tooltips as well.

Not possible at the current implementation.

So for the privacy, I decided to use the "eye" icons as the shield was a bit confusing.

I think we can now close this issue. Please open a new one if you have any more suggestions to improve the UI.
