### ISSUE TITLE
privacy.trackingprotection.enabled = off, to show ebay images?

### ISSUE THREAD

**Issue by D1GITALelementz** [schomery/privacy-settings#15]
Hi there...

Just updated Firefox to v41.0.1....... before the update I could use ebay.co.uk with full privacy enabled and images would be showing up as normal... say, from a search etc

Now... I can only use full privacy enabled with... "privacy.trackingprotection.enabled" = off ...otherwise images for me are not showing.

Any hep much appreciated.
Regards

**Comment by Snapy** [comment]
Install Config Mania from AMO. Open its settings, go to the "Security" tab -> "Privacy" section. You should see an "Exceptions" button for Tracking Protection where you can disable it for given domains.

**Comment by Gitoffthelawn** [comment]
As more people use this feature, sites will implement better design.

**Comment by D1GITALelementz** [comment]
Ok... cheers for the replies... =]

**Comment by Psycho-Mg** [comment]
[gtest_1.8.0-1-src.zip](https://github.com/schomery/privacy-settings/files/1497763/gtest_1.8.0-1-src.zip)
