### ISSUE TITLE
trackingprotection vs privacy

### ISSUE THREAD

**Issue by jomo** [schomery/privacy-settings#16]
From the [Security/Tracking proteciton](https://wiki.mozilla.org/Security/Tracking_protection) wiki:
> Tracking Protection is a new platform-level technology that blocks HTTP loads at the network level. It is **based on the Safe Browsing technology** that powers our phishing and malware protection.

The [difference](https://wiki.mozilla.org/Security/Tracking_protection/Client_implementation) is that:
> Firefox fetches the tracking protection list mozpub-track-digest256 **from a Mozilla Safe Browsing server**, and the existing phishing list from the Google Safe Browsing server

Using the `Privacy` option in this plugin disables `Safe Browsing` and `Stats Collection`, while `privacy.trackingprotection.enabled` option is `true` in any case.
It does make some sense, as it blocks third party trackers, but it still connects to Mozilla servers, similar to the stats collection.

I think this should at least be noted in the flag's description.

**Comment by schomery** [comment]
Thanks for the report. The `privacy.trackingprotection.enabled` description is now updated,
https://github.com/schomery/privacy-settings/blob/master/src/locale/en-US.properties#L22
