### ISSUE TITLE
treat_unsafe_negotiation_as_broken can be enabled in Compatible mode

### ISSUE THREAD

**Issue by jomo** [schomery/privacy-settings#17]
`security.ssl.treat_unsafe_negotiation_as_broken`

From the [Security:Renegotiation](https://wiki.mozilla.org/Security:Renegotiation#security.ssl.treat_unsafe_negotiation_as_broken) wiki:

> This preference can be used to achieve **visual feedback** …

As far as I understand, this does **not affect the connection** and only serves as an _indicator_ that
> raises awareness of servers that still need to be upgraded […] by displaying a red/broken padlock

Only the `security.ssl.require_safe_negotiation` option rejects connection attempts.

**Comment by schomery** [comment]
Thanks for catching this. Fixed on the latest dev version,
https://github.com/schomery/privacy-settings/blob/master/src/executables/extension.xpi?raw=true

You can try it by downloading the XPI and dropping it in your Firefox
