### ISSUE TITLE
Disable webRTC, speculative pre-connections, and visited links

### ISSUE THREAD

**Issue by flyingzebras** [schomery/privacy-settings#18]
What do you think about adding settings to Privacy Setting seen in https://addons.mozilla.org/en-US/firefox/user/ChrisAntaki/

* Disable WebRTC - https://github.com/ChrisAntaki/disable-webrtc-firefox
* Disable Speculative Pre-connections - https://github.com/ChrisAntaki/disable-speculative-pre-connections
* Disable Visited Links - https://github.com/ChrisAntaki/visited-links-firefox

**Comment by ChrisAntaki** [comment]
Just a heads up, Mozilla removed the security feature which powered Disable Plugin & Mimetype Enumeration

**Comment by flyingzebras** [comment]
@ChrisAntaki Thank you, I removed that from the list.

**Comment by flyingzebras** [comment]
@schomery Please add a thanks to @ChrisAntaki for his contribution if you add some of these settings to your software.

**Comment by schomery** [comment]
@flyingzebras I added `layout.css.visited_links_enabled` to the UI

> Disable Speculative Pre-connections

we already have `network.dns.disablePrefetch` and `network.prefetch-next`. There is no need for `network.http.speculative-parallel-limit`

> Disable WebRTC

We already have `media.peerconnection.enabled`

> Please add a thanks to @ChrisAntaki for his contribution (and the name of his add-ons) if you add some of these settings to your software.

done, https://github.com/schomery/privacy-settings/blob/master/src/package.json#L17
