### ISSUE TITLE
Request to add java script enable/disable

### ISSUE THREAD

**Issue by exodius48** [schomery/privacy-settings#2]
Hi.. can you add enable / disable java script? Its important for me

**Comment by inbasic** [comment]
It is now available on the latest developer version,
https://github.com/schomery/privacy-settings/blob/master/src/executables/extension.xpi?raw=true

**Comment by schomery** [comment]
It is now available on the latest developer version,
https://github.com/schomery/privacy-settings/blob/master/src/executables/extension.xpi?raw=true

**Comment by exodius48** [comment]
Yes it works, but I get it on Firefox 40b2

[img]http://s21.postimg.org/ee03oy27r/2015_07_08_150255.png[/img]

**Comment by schomery** [comment]
That is probably because it has not yet been signed by Mozilla. For better Policy Control you can try my newly submitted extension as well, https://addons.mozilla.org/en-US/firefox/addon/policy-control/

**Comment by exodius48** [comment]
For now, i use you add-on policy control. I think its more simple. 
Btw, i still get same condition like on screenshot above, hope firefox signed your all addons.

**Comment by Gitoffthelawn** [comment]
@exodius48 Just FYI, there are quite a few existing extensions that will allow you to quickly toggle javascript.

**Comment by schomery** [comment]
@Gitoffthelawn turning JS off globally breaks many sites. You can try https://addons.mozilla.org/en-US/firefox/addon/policy-control/ to define custom rules or block third-party scrips only

@exodius48 I have removed JS support from Privacy Settings extension. Using Policy Control extension is more effective.

**Comment by Gitoffthelawn** [comment]
@schomery Thanks!  I haven't experimented with policy control yet, but it looks excellent.  At one time I used an extension called ExExceptions that did something similar.  Policy Control looks much more refined and powerful.
