### ISSUE TITLE
WebRTC prefs

### ISSUE THREAD

**Issue by Gitoffthelawn** [schomery/privacy-settings#21]
You may find this to be a worthwhile read: https://wiki.mozilla.org/Media/WebRTC/Privacy

In particular, notice `media.peerconnection.ice.default_address_only`

It *could* be all that is needed (instead of `setting media.peerconnection.enabled` to false).

I have not fully tested it at this time.

What do others think?

**Comment by schomery** [comment]
Is there any problem with the current pref? `setting media.peerconnection.enabled`

**Comment by Gitoffthelawn** [comment]
I believe it *may* be overkill and is disabling extra functionality without any *known* benefits.  I have not had time to fully research this, however.  This is simply my preliminary understanding.

**Comment by ekaris** [comment]
Statutory addon doesn't disable webrtc completely, just removes the private IP info: http://www.ghacks.net/2015/11/02/take-control-of-webrtc-ip-leaks-with-statutory-for-firefox/

Would be great to have that option on privacy-settings

**Comment by Gitoffthelawn** [comment]
@schomery 
> Is there any problem with the current pref? setting media.peerconnection.enabled

Yes, please see https://github.com/schomery/privacy-settings/issues/55

**Comment by schomery** [comment]
> Statutory addon doesn't disable webRTC completely, just removes the private IP info

@ekaris added to 0.2.3b4

**Comment by schomery** [comment]
As of 0.2.3b4 it is possible to completely disable webRTC by disabling ``media.peerconnection.enabled` or just remove private ips by enabling both `media.peerconnection.ice.default_address_only` and `media.peerconnection.enabled` prefs
