### ISSUE TITLE
new verison 0.1.7.1 released today breaks RES (reddit enhancement suite)

### ISSUE THREAD

**Issue by roygbiv39** [schomery/privacy-settings#23]
The new version 0.1.7.1 released today breaks the Reddit Enhancement Suite when full privacy is enabled.

**Comment by Gitoffthelawn** [comment]
Try experimenting with the different individual settings to determine which one is interfering, and report back.

**Comment by schomery** [comment]
That's probably because of `dom.storage.enabled` pref. Try enabling it and restart your Firefox.

**Comment by Gitoffthelawn** [comment]
That's my guess too.
