### ISSUE TITLE
Unnecessary Tweak

### ISSUE THREAD

**Issue by IDKwhattoputhere** [schomery/privacy-settings#27]
Modifying toolkit.telemetry.enabled seems unnecessary since datareporting.healthreport.uploadEnabled=false will also set toolkit.telemetry.enabled=false
You can also see this in Firefoxs settings under about:preferences#advanced where health reports need to be send in order to send telemetry data.

**Comment by schomery** [comment]
I am not 100% sure if we can remove this pref. See https://github.com/schomery/privacy-settings/issues/22

**Comment by IDKwhattoputhere** [comment]
Interestingly toolkit.telemetry.archive.enabled and toolkit.telemetry.unified don't even exist in my about:config, not even with a fresh profile. Was it added in a newer version (using 38.4.0 ESR)?

**Comment by schomery** [comment]
I am not sure about the version number but they are now part of Firefox, http://gecko.readthedocs.org/en/latest/toolkit/components/telemetry/telemetry/preferences.html

**Comment by IDKwhattoputhere** [comment]
I see. I guess I can close this now. If someone wants this to be open just say so.
