### ISSUE TITLE
Considerations for Firefox forks

### ISSUE THREAD

**Issue by WagnerGMD** [schomery/privacy-settings#29]
Hello,

this a report about a browser like Cyberfox (PaleMoon etc). With the latest version (Cyberfox v43), these settings don't exist :
`camera.control.autofocus_moving_callback.enabled`
`datareporting.healthreport.service.enabled`
`datareporting.healthreport.uploadEnabled`
`network.websocket.enabled`

And those settings are already disable (false by default):
`loop.enabled`
`media.eme.enabled`
`media.gmp-eme-adobe.enabled`
`toolkit.telemetry.enabled`

You should take care of that because it can cause some trouble (error login etc). I assume, it was the websocket to blame.

**Comment by LimboSlam** [comment]
@WagnerGMD: Hm, so how did you get Privacy Setting to work with Pale Moon by the way? But yes, those definitely don't exist in Pale Moon.

**Comment by WagnerGMD** [comment]
@LimboSlam; There's a confusion, sorry. PaleMoon is mentionned only as an example here (nothing else). ATM I was mainly focus about CyberFox and I wasn't aware.

**Comment by Gitoffthelawn** [comment]
This is a good issue and discussion, but perhaps the title should be adjusted?

**Comment by LimboSlam** [comment]
@WagnerGMD: Yeah Pale Moon is incompatible with Privacy Settings. If you could please lower the requirement version to 24.0 and add our GUID to the install.rdf so us moonies can install this wonderful and powerful security/privacy tool. Though I'm not sure that would even work since it was written after Mozilla adopted the Australis theme/UI.   

By the way, who is the actual developer here? Sorry if it's not obvious for me, but I'm still getting around GitHub.

**Comment by WagnerGMD** [comment]
@Gitoffthelawn: Thank you and if you have any idea (or suggestion), you're welcome.

@LimboSlam; I can't. I'm just a normal user and absolutely not the developer. Privacy Settings was created (and probaby also mainted as today) by **schomery**.
 I understand, GitHub require sometimes to get used to. 

After check, I'm able to edit the title. So let me know would be better and I will fix this. At least, it does sound better.

**Comment by Gitoffthelawn** [comment]
@LimboSlam and @WagnerGMD 

I didn't expect so much interest in my comment. :-)

Correct, @WagnerGMD can adjust the title of his/her own issue posts (as can the project owner).

Something like "Issues to consider for Firefox forks" or "Considerations for Firefox forks" or "Important differences with Firefox forks" will all work.

**Comment by LimboSlam** [comment]
Yes something in those therms @Gitoffthelawn and @WagnerGMD. The 2nd one sounds good.

**Comment by WagnerGMD** [comment]
@Gitoffthelawn and @LimboSlam: It's done and thank you, the 2nd sounds good for me too (so I chose this one).

@Gitoffthelawn It's totally normal :-). From my point of view, It's like a principle.

**Comment by schomery** [comment]
Guys to support Pale Moon we just need one missing module. I have already opened a bug report, but still no answer / comment
https://github.com/MoonchildProductions/Pale-Moon/issues/295

> this a report about a browser like Cyberfox (PaleMoon etc). With the latest version (Cyberfox v43), these settings don't exist : `network.websocket.enabled`

so disabling a pref that does not exist cause error logs?

**Comment by LimboSlam** [comment]
@schomery and @Gitoffthelawn: Yes thank you for that, really appreciate it. I just want to say that Moonchild (our lead developer) is quite busy stabilizing our new major release of Pale Moon. This version (26.0.0) brings forth a new layout/rendering engine called https://moonchildproductions.info/goanna.shtml-automatic [Goanna] (https://moonchildproductions.info/goanna.shtml) to further diverge from Firefox, prevent confusion of what layout/rendering engine (source code) that Pale Moon runs off and now builds off and of course legal reasons. To mark another milestone of independent development (Pale Moon isn't affiliated with or subject to either code releases or publication plans of the Mozilla Corporation).

Hope you all can understand and please be patient with me. I know it's hard!  :)

**Comment by schomery** [comment]
quoting...
 
> We'll be dropping SDK extension support in the rebase, so this has become a non-issue.
