### ISSUE TITLE
Menu panel text

### ISSUE THREAD

**Issue by Gitoffthelawn** [schomery/privacy-settings#3]
Version 0.1.3 partially fixed the bug in the menu panel in which the wrong text was displayed under the icon.

There is still a small bug: on some systems, the text under the icon displays as:
```
     Privacy Set-
     tings
```
Instead of:
```
    Privacy Settings
```
or
```
    Privacy
    Settings
```

**Comment by schomery** [comment]
I am not sure why the text is not shown correctly. The extension uses the standard method to insert the toolbar button. Do you have this problem with another extension as well?

**Comment by Gitoffthelawn** [comment]
Good question.

I don't have this issue with any other extensions.  I have several extensions and Firefox functions in the menu panel, but Privacy Settings is the only one with this issue.  All of the other menu panel items use two lines if the text does not fit in the first line.  None of them hyphenate the text like Privacy Settings.

**Comment by schomery** [comment]
Seems like this happens for other extensions too,
![screen shot 2015-07-20 at 15 32 17](https://cloud.githubusercontent.com/assets/11704051/8774625/7cb979cc-2ef5-11e5-9f65-3ef8a1df824b.png)

**Comment by Gitoffthelawn** [comment]
Interesting.  I wonder if it's a Firefox bug or if simply both of those extensions have the same issue.  None of the native Firefox functions seem to get hyphenated that way, and neither do any extensions I tested.  But clearly there is at least one other extension that has the same issue as Privacy Settings.  I honestly don't know if it's a Firefox bug or not.  It sure is ugly, but thankfully it does not affect functionality in any way.

**Comment by tumpio** [comment]
All menu panel items are set to be automatically hyphenated:

```
.panelUI-grid .toolbarbutton-1:not([auto-hyphens="off"]) > .toolbarbutton-menubutton-button > .toolbarbutton-multiline-text,
.panelUI-grid .toolbarbutton-1:not([auto-hyphens="off"]) > .toolbarbutton-multiline-text {
  -moz-hyphens: auto;
}
```

**Comment by Gitoffthelawn** [comment]
Thanks for finding that.

Here's the CSS code to get rid of the hyphens if anyone wants to add it to their userchrome:

```
/* menu panel items: remove hyphenation from text
      selectors from mxr.mozilla.org/mozilla-release/source/browser/themes/shared/customizableui/panelUIOverlay.inc.css */
.panelUI-grid .toolbarbutton-1 > .toolbarbutton-menubutton-button > .toolbarbutton-multiline-text,
   .panelUI-grid .toolbarbutton-1 > .toolbarbutton-multiline-text {
      -moz-hyphens: none !important; }
```
