### ISSUE TITLE
rationale behind disabling dom.event.clipboardevents.enabled

### ISSUE THREAD

**Issue by monperrus** [schomery/privacy-settings#31]
Disabling dom.event.clipboardevents.enabled breaks copy'n'paste in many sites, such as Github inline editor, Gmail, etc. 

What's the privacy rationale behind disabling dom.event.clipboardevents.enabled?

**Comment by schomery** [comment]
http://www.ghacks.net/2014/01/08/block-websites-reading-modifying-clipboard-contents-firefox/

**Comment by monperrus** [comment]
does this mean that a page can read my clipboard? (which sometimes
contains passwords...)

**Comment by schomery** [comment]
Not directly from Clipboard, but when you press `Ctrl + C` or `Ctrl + V`, scripts on **the active** page have access to the content.

You can try it yourself. Just open the Web Console and paste the following code:

```javascript
document.addEventListener('copy', function(e){
    console.error(e);
});
document.addEventListener('pase', function(e){
    console.error(e);
});
```

**Comment by schomery** [comment]
I am going to enable `dom.event.clipboardevents.enabled` on compatible modes for the next version though.

Thanks for the report.

**Comment by Neustradamus** [comment]
If it is disabled (dom.event.clipboardevents.enabled = false), there is a problem with:
- Facebook.com
- Twitter.com
