### ISSUE TITLE
[Idea] Change preset

### ISSUE THREAD

**Issue by IDKwhattoputhere** [schomery/privacy-settings#32]
"Privacy & Security" should be "Privacy (compatible) & Security" since that would be most advisable to less experienced users.
At the moment you have those options:
- "Full Privacy" which breaks sites (which e.g. use unsafe negotiation).
- "Privacy & Security"  which breaks sites (which e.g. use unsafe negotiation).
- "Privacy (compatible)" which is currently the best option for less experienced users but disables Google Safe browsing which might not be a good thing for those people.

What do you think?

**Comment by schomery** [comment]
I agree with you, but I think "Privacy & Security" button is also a must have. Let have one more button instead.

You can try this dev version here, https://github.com/schomery/privacy-settings/blob/master/src/executables/extension.xpi?raw=true

![screen shot 2016-01-19 at 18 39 25](https://cloud.githubusercontent.com/assets/11704051/12422470/5efaee12-bedc-11e5-9bab-e79de95efa37.png)

**Comment by IDKwhattoputhere** [comment]
Awesome. I really like it. :smiley: 


One very minor thing: To be consistent with the tooltips how about replacing them with:

- `and have 'Google Safe Browsing' enabled` with `while having 'Google Safe Browsing' enabled` to make it consistent with "Privacy & Security" (I have kind of a problem with this one because someone might think that 'Google Safe Browsing' is source of web page breakage. Maybe you know some better phrasing.)

- `but turning off those settings [...]` with `without breaking secure sites` to make it consistent with "Privacy (compatible) & Security"

- add `(this option disables 'Google Safe Browsing')` to "Privacy (compatible)" to make it consistent with "Full Privacy"

This way it's easier and quicker to choose the right preset.

**Comment by schomery** [comment]
Right, how about now?
https://github.com/schomery/privacy-settings/blob/master/src/locale/en-US.properties#L51

**Comment by IDKwhattoputhere** [comment]
How about this:
```
To bring maximum privacy without breaking secure websites plus keep "Google Safe Browsing" enabled for security checks (recommended mode)
To bring maximum privacy without breaking secure websites (this option disables "Google Safe browsing")
To bring maximum privacy (can break some secure websites) plus keep "Google Safe Browsing" enabled for security checks
To bring maximum privacy (can break some secure websites) (this option disables "Google Safe browsing")
Reset all preferences back to factory defaults
```
Looks more structured to me.

**Comment by schomery** [comment]
Thanks, https://github.com/schomery/privacy-settings/blob/master/src/locale/en-US.properties#L51-L59

**Comment by IDKwhattoputhere** [comment]
No, thanks to you. :)
