### ISSUE TITLE
Settings from another somewhat similar extension

### ISSUE THREAD

**Issue by Gitoffthelawn** [schomery/privacy-settings#41]
The[ PrivaConf extension](https://addons.mozilla.org/firefox/addon/privaconf/) has somewhat similar goals as this extension.

Here is it's list of the preferences it modifies: http://fonk.wz.cz/privaconf

**Comment by schomery** [comment]
I am not able to open the link. Is there anything we should consider?

Please list init preferences as well since we are going to have advanced settings soon.

**Comment by geokis** [comment]
Try to display the source code on **[addons.mozilla ](https://addons.mozilla.org/de/firefox/files/browse/404239/file/bootstrap.js)**. On the Webpage you only see some short additionally explanations.

Much settings are in PrivacySettings implemented, some settings can find in **speedyFox**
I think settings about  _cookie-behavior_ and _browser-cache_ are not  necessary.

Resp. for Cookies you find much better Addons: **[Self-Destructing Cookies](https://addons.mozilla.org/de/firefox/addon/self-destructing-cookies/)**

**Comment by schomery** [comment]
I have reviewed all the settings and added a few in the advanced panel. Please double check the current settings and let me know if anything related to this extension is missed.
https://github.com/schomery/privacy-settings/issues/42
