### ISSUE TITLE
Panel not showing up

### ISSUE THREAD

**Issue by ajay340** [schomery/privacy-settings#43]
I downloaded the addon, but the icon doesn't appear on the top right nor the sidebar. Is there any way I can access the Panel. I tried removing and installing the addon again, but nothing is working.

**Comment by schomery** [comment]
If the panel is not showing up, it means the extension has probably not been initiated. There is certainly a conflict with another extension or for some reason your Firefox profile is damaged. What is your Firefox version?

The easiest way to resolve this usually is to try the extension on a clean profile. If it works fine there we can debug your current profile as well
http://blog.add0n.com/2016/01/30/how-to-use-firefox-profile-manager.html

**Comment by MindTooth** [comment]
I know it's bad to bump closed issues.  But I managed to make it show again in OS X.  I had to disable the Omnibar addon, the one from 2014.

**Comment by schomery** [comment]
Thanks for sharing
