### ISSUE TITLE
User settings are resetting every time the browser is launched.

### ISSUE THREAD

**Issue by Rosshill98** [schomery/privacy-settings#47]
For example, if I select "full privacy" and then I change some settings, those settings will not change for the rest of the browser session. But if I quit and reopen my browser, all of the settings will be set to "full privacy" without any of the changes I made.

**Comment by schomery** [comment]
Seems like your Firefox profile is damaged. Can you try the extension on a clean profile?
http://blog.add0n.com/2016/01/30/how-to-use-firefox-profile-manager.html

**Comment by Gitoffthelawn** [comment]
You could also have another extension changing the preferences, or have a user.js or a mozilla.cfg file changing them.

See:
http://kb.mozillazine.org/User.js_file
http://kb.mozillazine.org/Locking_preferences

**Comment by belaviyo** [comment]
I closed my Firefox and deleted (backed up) the prefs.js and it worked.
