### ISSUE TITLE
[enhancement] introduce a `performance` tag

### ISSUE THREAD

**Issue by mattia-b89** [schomery/privacy-settings#50]
first, thank you for your job!

I want to suggest you a new tag (a group in which setting belongs) called `performance` (or what else name... i.e. low latency) that gather together setting which can enhance speed of page loading or what else related to speed.

e.g.
enable DNT feature will improve page loading time since many connections (do third site) are cut off

**Comment by geokis** [comment]
This addon collects the settings for **privacy & security**

For performance settings use shomery's Addon **[SpeedyFox](https://github.com/schomery/speedyfox)**

**Comment by schomery** [comment]
as @geokis suggested, we've already covered most of speed related stuffs in the [SpeedyFox extension](https://addons.mozilla.org/en-US/firefox/addon/speed-tweaks-speedyfox/).
