### ISSUE TITLE
[enhancement] to the guide

### ISSUE THREAD

**Issue by mattia-b89** [schomery/privacy-settings#51]
I'd like to see your page pointing to this source https://wiki.mozilla.org/Media/EME
I think it is useful because underline that EME is platform/os dependant

**Comment by schomery** [comment]
Not clear what page and why

**Comment by mattia-b89** [comment]
I though on the plugin homepage, where you explain the parameters
meaning... I think is useful, first because is the direct link to *eme*
variables handled by your plugin and second it tells us that UNIX platform
doesn't support it!

sent from my E2
On 7 Jun 2016 9:06 a.m., "schomery" <notifications@github.com> wrote:

Not clear what page and why

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/schomery/privacy-settings/issues/51#issuecomment-224197781>,
or mute the thread
<https://github.com/notifications/unsubscribe/AAhSt_5cFqwL_KV_FTEpAsdF6n6plxIWks5qJRh4gaJpZM4Ip8Wg>
.

**Comment by schomery** [comment]
I see. Good point; FAQs page has been updated. http://firefox.add0n.com/privacy-settings.html#faq18
