### ISSUE TITLE
Cue icons only show unknown glyphs

### ISSUE THREAD

**Issue by MicroBeast** [schomery/privacy-settings#52]
Firefox 46.0.1
GNU/Debian Linux sid amd64.

Hello,
I mean the small icons inside "Privacy Settings". The eye, lock, or on/off icons.

How to produce:
Set Firefox setting "gfx.downloadable_fonts.enabled" to false. Probably also effected by entirely clear Firefox Caches. Restart Firefox. The mentioned icons will only shown in Unknown Glyph.
From your package, it seem Privacy Settings" supposed to fetch font icons from fontello-5.woff?.

Thank you.

**Comment by geokis** [comment]
Set `browser.display.use_document_fonts` to **0**
And `gfx.downloadable_fonts.enabled` to true

This will block regular **fonts**, but downloading **icon fonts**, icon fonts are needed to display the Addon correctly.

@schomery 
I think the options:
- `browser.display.use_document_fonts` 
- `gfx.downloadable_fonts.enabled`
should be integrated in PrivacySettings too. 
Set the options to false, prevents the sites to create fingerprinting, based on the user's Fonts folder.

**Comment by schomery** [comment]
@geokis Thanks for the suggestion. We have them on the advanced panel now.
https://github.com/schomery/privacy-settings/blob/master/builds/jid1-CKHySAadH4nL6Q@jetpack-0.2.2b1.xpi?raw=true
