### ISSUE TITLE
Disabling WebRTC (setting media.peerconnection.enabled to false) causing unexpected site failures

### ISSUE THREAD

**Issue by Gitoffthelawn** [schomery/privacy-settings#55]
I have noticed that ***too many*** sites are not working properly in Firefox 47.0.1.

After hours of work, I discovered that the culprit is setting `media.peerconnection.enabled` to `false`.  Doing this disables WebRTC, which is generally a good idea for both privacy and security reasons.

Interestingly, none of the failing sites actually use WebRTC.

This issue seems to be the result of *incredibly* poorly coded libraries that a number of popular sites use.

Just as an example, take a close look at [Airbnb](https://airbnb.com).  When `media.peerconnection.enabled` is set to `false`, it becomes impossible to set the dates for reservations on their main page.

When WebRTC is disabled, one of the JavaScript libraries used by that popular site throws an error, and it does not handle the error condition gracefully.  The result is a website that fails.

Although diagnosing the problem took a fair amount of effort, finding a solution may require even more effort.  Globally enabling WebRTC is a [bad idea for many reasons](https://www.browserleaks.com/webrtc), but disabling it is breaking popular sites.

Looking forward to a good discussion regarding this issue.

**Comment by ekaris** [comment]
This should be reported also on firefox bugzilla account

**Comment by Gitoffthelawn** [comment]
As a stop gap measure, I recommend this extension add: `media.peerconnection.ice.default_address_only` directly under `media.peerconnection.enabled`.

For another discussion of this issue, see: https://github.com/ChrisAntaki/disable-webrtc-firefox/issues/9

**Comment by schomery** [comment]
Since the VPN leakage is still under question, I added both prefs. In full privacy mode, both prefs are changed. But in the compatible mode we are only altering`edia.peerconnection.ice.default_address_only`

@Gitoffthelawn thanks for the report

**Comment by schomery** [comment]
https://github.com/schomery/privacy-settings/blob/master/builds/0.2.3b4.xpi?raw=true

**Comment by Gitoffthelawn** [comment]
You're welcome.  What you did sounds great.  I'll take a look at it in a few days when I have a moment.
