### ISSUE TITLE
Add option to disable proxy

### ISSUE THREAD

**Issue by ekaris** [schomery/privacy-settings#58]
New attack can reveal full address of HTTPS pages:
https://www.blackhat.com/us-16/briefings.html#crippling-https-with-unholy-pac

**Comment by schomery** [comment]
Thanks for the link. I assume showing the proxy config in the panel would be enough. For manipulating proxy it is better to install an extension. Currently clicking on the link will open Firefox's Options page.

![screen shot 2016-08-24 at 15 29 23](https://cloud.githubusercontent.com/assets/11704051/17928362/93b70080-6a0f-11e6-810a-0901ee0d8baf.png)

**Comment by ekaris** [comment]
I think it would be better to put an off option and the default automatic

**Comment by schomery** [comment]
okay then, lets have it as an int pref since there is no good default option here.

![screen shot 2016-08-24 at 16 01 20](https://cloud.githubusercontent.com/assets/11704051/17929446/dcb9f21e-6a15-11e6-940a-c23345b14bdf.png)

**Comment by ekaris** [comment]
Seems good and add a security and privacy to setting off

**Comment by schomery** [comment]
Deciding which types are more private or secure depends on user and the network. I think it is better to have neither security nor privacy badges.

**Comment by ekaris** [comment]
Ok, but can you put there a text explaining that option 0 protects the user from rogue local network attacks on learning the URL

**Comment by schomery** [comment]
This attack is only for type=2 (PAC), right? I think we should have it mentioned on type=2. For instance on type=1, no such a attach is applicable; https://github.com/schomery/privacy-settings/blob/master/src/locale/en-US.properties#L48-L54

**Comment by ekaris** [comment]
I'm not sure, only reading the whitepaper

**Comment by schomery** [comment]
Okay then we will have the warning on these three types.
Thanks for the report.
