### ISSUE TITLE
More info for dom.event.contextmenu.enabled is linking to wrong info

### ISSUE THREAD

**Issue by ekaris** [schomery/privacy-settings#59]
More info for dom.event.contextmenu.enabled/dom.disable_open_during_load is linking to wrong website info

**Comment by schomery** [comment]
Thanks for the report. I am going to change the link to this thread to be able to add all possible references in a single page.

References:
http://kb.mozillazine.org/About:config_entries
http://www.wikihow.com/Disable-%22No-Right-Click%22-Scripts-in-Firefox
