### ISSUE TITLE
Add option to disable CSS mix-blend-mode 

### ISSUE THREAD

**Issue by ekaris** [schomery/privacy-settings#62]
CSS Mix-Blend-Mode Feature Can Reveal Your Browsing History

**Comment by schomery** [comment]
Is there anyway to disable the `mix-blend-mode`? have you seen any extension that does this?

**Comment by schomery** [comment]
okay got it; https://bugzilla.mozilla.org/show_bug.cgi?id=952643

**Comment by schomery** [comment]
We will have this on the advanced settings page. Thanks

**Comment by Gitoffthelawn** [comment]
Here is a security report regarding this issue: http://lcamtuf.blogspot.com/2016/08/css-mix-blend-mode-is-bad-for-keeping.html

**Comment by jomo** [comment]
I'd like to add that you can also set `layout.css.visited_links_enabled=false` instead.
It will disable any visited link styling but has the advantage that you could still use mix-blend-mode and it would prevent any other potential leaks based on visited link styling.
