### ISSUE TITLE
undefined window exception on FreeBSD 11

### ISSUE THREAD

**Issue by camachat** [schomery/privacy-settings#67]
Runs OK on my Ubuntu Linux 16.04 and MS Windows 10, but on FreeBSD it's widget didn't show up, console log says "window is undefined".
$ firefox 

(firefox:3972): GVFS-RemoteVolumeMonitor-WARNING **: remote volume monitor with dbus name org.gtk.vfs.HalVolumeMonitor is not supported
console.error: ipsettings: 
  Message: TypeError: window is undefined
  Stack:
    id<@resource://jid1-ckhysaadh4nl6q-at-jetpack/lib/android.js:47:3
@resource://jid1-ckhysaadh4nl6q-at-jetpack/lib/android.js:46:11
@resource://jid1-ckhysaadh4nl6q-at-jetpack/lib/main.js:16:46
run@resource://gre/modules/commonjs/sdk/addon/runner.js:147:19
startup/</<@resource://gre/modules/commonjs/sdk/addon/runner.js:87:9
Handler.prototype.process@resource://gre/modules/Promise-backend.js:937:23
this.PromiseWalker.walkerLoop@resource://gre/modules/Promise-backend.js:816:7
this.PromiseWalker.scheduleWalkerLoop/<@resource://gre/modules/Promise-backend.js:750:11

*************************
A coding exception was thrown in a Promise resolution callback.
See https://developer.mozilla.org/Mozilla/JavaScript_code_modules/Promise.jsm/Promise

Full message: TypeError: window is undefined
Full stack: id<@resource://jid1-ckhysaadh4nl6q-at-jetpack/lib/android.js:47:3
@resource://jid1-ckhysaadh4nl6q-at-jetpack/lib/android.js:46:11
@resource://jid1-ckhysaadh4nl6q-at-jetpack/lib/main.js:16:46
run@resource://gre/modules/commonjs/sdk/addon/runner.js:147:19
startup/</<@resource://gre/modules/commonjs/sdk/addon/runner.js:87:9
Handler.prototype.process@resource://gre/modules/Promise-backend.js:937:23
this.PromiseWalker.walkerLoop@resource://gre/modules/Promise-backend.js:816:7
this.PromiseWalker.scheduleWalkerLoop/<@resource://gre/modules/Promise-backend.js:750:11

*************************
console.error: ipsettings: 
  Message: TypeError: window is undefined
  Stack:
    id<@resource://jid1-ckhysaadh4nl6q-at-jetpack/lib/android.js:47:3
@resource://jid1-ckhysaadh4nl6q-at-jetpack/lib/android.js:46:11
@resource://jid1-ckhysaadh4nl6q-at-jetpack/lib/main.js:16:46
run@resource://gre/modules/commonjs/sdk/addon/runner.js:147:19
startup/</<@resource://gre/modules/commonjs/sdk/addon/runner.js:87:9
Handler.prototype.process@resource://gre/modules/Promise-backend.js:937:23
this.PromiseWalker.walkerLoop@resource://gre/modules/Promise-backend.js:816:7
this.PromiseWalker.scheduleWalkerLoop/<@resource://gre/modules/Promise-backend.js:750:11

**Comment by schomery** [comment]
Thanks for the report. This issue should have been fixed on the latest dev version. Please give it a try and let me know if the issue persists.

https://github.com/schomery/privacy-settings/blob/master/builds/0.2.4b1.xpi?raw=true

To install open a browser tab for about:debuggings, check the developer mode on and point the browse button to the downloaded XPI.

**Comment by Gitoffthelawn** [comment]
Just a small correction, you'll need `about:debugging` instead of `about:debuggings`

**Comment by camachat** [comment]
It works now, thanks!
