### ISSUE TITLE
Add dom.battery.enabled

### ISSUE THREAD

**Issue by agilob** [schomery/privacy-settings#7]
>There’s a feature on HTML5, the standard web programming language, that enables websites to know information about the battery in your laptop or smartphone, security researchers claim in a new paper that was first reported by The Guardian.

http://uk.businessinsider.com/smartphone-battery-data-for-tracking-2015-8?op=1?r=US&IR=T

https://developer.mozilla.org/en-US/docs/Web/API/Navigator/battery

**Comment by Gitoffthelawn** [comment]
+1

Toggling that API would be appropriate.

**Comment by schomery** [comment]
Thanks, it is now available in the dev built,
https://github.com/schomery/privacy-settings/blob/master/src/executables/extension.xpi?raw=true

**Comment by agilob** [comment]
Nice, thanks for really quick reaction. If you want to add some more settings related to privacy I [gathered some on my blog recently](http://b.agilob.net/better-security-privacy-and-anonymity-in-firefox/), take a look at section 2 and 11.
