### ISSUE TITLE
Add icon column for default state

### ISSUE THREAD

**Issue by Gitoffthelawn** [schomery/privacy-settings#74]
Right now, we have the lock and eye icons for privacy and security states, respectively.

How about a third column: an icon to represent if the current setting is the Firefox default.

This way, users will know if their settings differ or conform to the defaults set by Mozilla.

**Comment by schomery** [comment]
We have this on the new WebExtension design;
https://github.com/schomery/privacy-settings/issues/80

**Comment by Gitoffthelawn** [comment]
Wonderful!  Thank you!
