### ISSUE TITLE
Safebrowsing prefs require updating for Firefox 50+

### ISSUE THREAD

**Issue by Gitoffthelawn** [schomery/privacy-settings#76]
Currently, for Firefox 50+, PrivacySettings makes it look like phishing protection is off when it may (or may not) be on.

Firefox 49 and earlier:

    browser.safebrowsing.enabled: enable phishing protection

Firefox 50 and later:

    browser.safebrowsing.phishing.enabled: enable phishing protection

See https://wiki.mozilla.org/Safe_Browsing

**Comment by jango25** [comment]
It seems the author abandoned his creation.

**Comment by schomery** [comment]
nope! I am waiting for FF 51 release. In 51, we can have embedded WebExtension which improves the performance of this extension. Since many changes need to be done to make this extension compatible with FF 51, I'll push the next update when 51 reaches the release channel.

**Comment by jango25** [comment]
O! Forgive me then. Waiting for the new release.

**Comment by Atavic** [comment]
@Gitoffthelawn You can get very similar results with a google search.
The malware/phishing/unwanted urls are greyed out in search results.

**Comment by schomery** [comment]
Fixed on the new WebExtension replacement; https://github.com/schomery/privacy-settings/issues/80

Thanks for the report.

**Comment by Gitoffthelawn** [comment]
Fantastic!  And, of course, you're welcome. :)
