### ISSUE TITLE
WebRTC leaks local IP addresses (Firefox 51)

### ISSUE THREAD

**Issue by IDKwhattoputhere** [schomery/privacy-settings#77]
In Firefox 51 a new setting is needed to prevent local IP address leakage with WebRTC. This can be observed when visiting a site like `ipleak.net` with Firefox 51 before and after enabling `Privacy (compatible)` mode in the extension. Local IP address will leak unless `media.peerconnection.enabled` or the new setting `media.peerconnection.ice.no_host` is changed.

For more info see here: https://github.com/gorhill/uBlock/issues/2337

**Comment by schomery** [comment]
We will have this new pref in the WebExtension version that supports FF > 51; https://github.com/schomery/privacy-settings/issues/80

Thanks for the report.
