### ISSUE TITLE
add network.http.speculative-parallel-limit

### ISSUE THREAD

**Issue by agilob** [schomery/privacy-settings#8]
http://www.hackcave.net/2015/08/firefox-stealthily-loads-webpages.html

**Comment by tumpio** [comment]
With a quick glance the extension expects preferences to be boolean type?

network.http.speculative-parallel-limit is integer type.

**Comment by schomery** [comment]
Yes, currently the panel only accepts Boolean types.

**Comment by Gitoffthelawn** [comment]
How does that setting relate to `network.prefetch-next`, and should this pref be added to the extension?

**Comment by schomery** [comment]
The latest dev version supports `network.dns.disablePrefetch` and `network.prefetch-next`. If there is any other related Boolean pref, reopen this bug.

**Comment by Gitoffthelawn** [comment]
Do the two boolean prefs that were added remove the need for setting *network.http.speculative-parallel-limit*  (IOW, make it irrelevant since the parent setting can be disabled)?

**Comment by schomery** [comment]
@Gitoffthelawn I am not really sure. I couldn't find any way to test this.
