### ISSUE TITLE
Add option for captive portal detection

### ISSUE THREAD

**Issue by yfdyh000** [schomery/privacy-settings#81]
pref `network.captive-portal-service.enabled`

https://bugzilla.mozilla.org/show_bug.cgi?id=989193
https://bugzilla.mozilla.org/show_bug.cgi?id=562917
https://hg.mozilla.org/mozilla-central/rev/89d1a91a97d2#l7.13

**Comment by schomery** [comment]
Thanks we will have this in the advanced settings page.
