### ISSUE TITLE
network.http.referer.userControlPolicy

### ISSUE THREAD

**Issue by jawz101** [schomery/privacy-settings#82]
https://developer.mozilla.org/en-US/Firefox/Releases/53

Just wanted to throw this out here

Gecko now has a pref available in about:config to allow users to set their default Referrer-Policy — network.http.referer.userControlPolicy (bug 1304623). Possible values are:
    0 — no-referrer
    1 — same-origin
    2 — strict-origin-when-cross-origin
    3 — no-referrer-when-downgrade (the default)

**Comment by schomery** [comment]
Thanks! we will have this on the advanced page.
