### ISSUE TITLE
network.IDN_show_punycode

### ISSUE THREAD

**Issue by anonsubmitter** [schomery/privacy-settings#83]
You might want to add **network.IDN_show_punycode** to Privacy Settings and set it to **true** in order to prevent [phishing attempts from sites using unicode domain names](https://www.wordfence.com/blog/2017/04/chrome-firefox-unicode-phishing/).
[The Bugzilla issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1332714) is low priority, so I doubt there will be a fix from Mozilla's side for a while.

**Comment by schomery** [comment]
Thanks! we will have this on the next release
