### ISSUE TITLE
Adaptation to Pale Moon 

### ISSUE THREAD

**Issue by graciecat** [schomery/privacy-settings#86]
I would like to use this excellent add-on in [Pale Moon](http://www.palemoon.org/technical.shtml) browser, a fork of Firefox with [significant differences](http://www.palemoon.org/technical.shtml#Firefox_Differences). Would you be interested in porting your add-on over to be Pale Moon compatible? 

I am referring to the SDK version of Privacy Settings—particularly [version 0.2.0](https://addons.mozilla.org/en-US/firefox/addon/privacy-settings/versions/0.2.0)

Although PM does not support Mozilla Add-on SDK, there is [PMKit](http://developer.palemoon.org/Add-ons:Extensions/Jetpack) for adapting JetPack extensions (basically, a library that provides basic compatibility layer with Mozilla Add-on SDK).

I noticed you had a not-so-great [conversation](https://github.com/MoonchildProductions/Pale-Moon/issues/295) last year about adapting your SDK add-ons to Pale Moon, but that was before they created the PMKit to make it easy on developers. (I hope you will not let the discouragement you received last year deter you now.) 

Many developers have successfully adapted their JetPack extensions for PM, as you can see here: https://github.com/JustOff/pm27-sdk-addons/blob/master/README.md

**Comment by schomery** [comment]
Seems like Privacy Settings works just fine on PM. I will add PM compatibility to the upcoming version then!

**Comment by graciecat** [comment]
That's great! Thanks! If you would like to have it listed at the[ Pale Moon Add-ons Site](https://addons.palemoon.org/), see [these instructions here](http://developer.palemoon.org/Add-ons:Site#head:Submitting_your_Add-on).
