### ISSUE TITLE
deprecated about:config entries

### ISSUE THREAD

**Issue by jawz101** [schomery/privacy-settings#87]
security.tls.unrestricted_rc4_fallback
security.tls.insecure_fallback_hosts.use_static_list
_deprecated in FFox 44
https://bugzilla.mozilla.org/show_bug.cgi?id=1165421
https://bugzilla.mozilla.org/show_bug.cgi?id=999544_

media.gmp-eme-adobe.enabled
I don't even remember when they used an adobe plugin but FFox uses the widevine plugin at media.gmp-widevinecdm.enabled

datareporting.healthreport.service.enabled
is this even vaild??  I've just been checking all of these by right-clicking and resetting the pref.  if the pref goes away (doesn't toggle) it's old or maybe an undocumented preference I guess :/

loop.facebook.shareUrl
loop.logDomains
social integration was disabled a while ago

**Comment by Atavic** [comment]
datareporting.healthreport.service is deprecated from FF46:
https://github.com/ghacksuserjs/ghacks-user.js/issues/123

**Comment by Thorin-Oakenpants** [comment]
>  if the pref goes away (doesn't toggle) it's old or maybe an undocumented preference I guess

Some preferences are "hidden preferences". To be absolutely sure a preference is deprecated/removed you need to confirm it from the source (bugzilla) and check the source ([DXR central](https://dxr.mozilla.org/mozilla-central/source/))

But to save you time, earthlng and I did it all for you - see Atavic's link above

> I don't even remember when they used an adobe plugin

Adobe's EME (Encryption Media Extension) is a CDM (Content Decryption Module) GMP (Gecko Media Plugin) just the same as Widevine is.
