### ISSUE TITLE
What about beacons?

### ISSUE THREAD

**Issue by Gitoffthelawn** [schomery/privacy-settings#9]
The new beacons can be disabled by setting
user_pref("beacon.enabled", false);

Note that these are not the old "image" beacons.  Same word, completely different technology.

Here's a thread about them: http://www.wilderssecurity.com/threads/hyperlink-auditing-aka-a-ping-and-beacon-aka-navigator-sendbeacon.364904/

**Comment by schomery** [comment]
Thanks! this is a must have. We have it on the dev built now,
https://github.com/schomery/privacy-settings/blob/master/src/executables/extension.xpi?raw=true

Also if you have [Policy Control](https://addons.mozilla.org/en-US/firefox/addon/policy-control/) addon installed, there is an option to disable ping requests there

**Comment by Gitoffthelawn** [comment]
You're welcome.  Thanks for the great extension!

Just so we're on the same page, ping requests are totally different from beacons.  Are we in agreement?

**Comment by schomery** [comment]
Yes, I meant the new "Policy Control" supports both ping and beacon blockage.

**Comment by Gitoffthelawn** [comment]
Great!
