### ISSUE TITLE
Feature Request: Simple Mode

### ISSUE THREAD

**Issue by LeoReentry** [schomery/privacy-settings#92]
How about a simple mode, where the whole panel disappears and instead just a Toggle Switch is displayed with three positions:
Normal - Enhanced Privacy (The Privacy(Compatible) mode) - Full Privacy

This way, I could install the extension on my girlfriend's PC and on my family members' PCs without them being angry at me for breaking their internet again.

I think this could be a huge usability improvement for users that don't understand how thinks work.

**Comment by bobmac1547** [comment]
Agreed!!

**Comment by schomery** [comment]
Is it useful to have these options in the right-click menu instead?

**Comment by schomery** [comment]
![screen shot](https://user-images.githubusercontent.com/11704051/34814660-b8cd4fae-f6c3-11e7-9dd3-21e43e5b3633.png)
